// <auto-generated />
using System;
using HackMidwest2018Backend.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackMidwest2018Backend.Migrations
{
    [DbContext(typeof(PartyContext))]
    [Migration("20180721193359_AddEventAndModels")]
    partial class AddEventAndModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerContactId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerContactId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Contact", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
