// <auto-generated />
using System;
using HackMidwest2018Backend.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackMidwest2018Backend.Migrations
{
    [DbContext(typeof(PartyContext))]
    [Migration("20180721202226_dbRename")]
    partial class dbRename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int?>("OwnerContactId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerContactId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventId");

                    b.Property<int?>("ScheduleId1");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EventId");

                    b.HasIndex("ScheduleId1");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Contact", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerContactId");
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Schedule", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Schedule")
                        .WithMany("Schedules")
                        .HasForeignKey("ScheduleId1");
                });
#pragma warning restore 612, 618
        }
    }
}
