// <auto-generated />
using System;
using HackMidwest2018Backend.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HackMidwest2018Backend.Migrations
{
    [DbContext(typeof(PartyContext))]
    partial class PartyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ContactId");

                    b.HasAlternateKey("Email")
                        .HasName("AltKey_Contact_Email");

                    b.ToTable("Contacts");

                    b.HasData(
                        new { ContactId = 1, Email = "ItsMeATeddy@gmail.com", FirstName = "Teddy", LastName = "Ivarock", PhoneNumber = "5555555555" },
                        new { ContactId = 2, Email = "tripleTheCharliTripleTheFun@gmail.com", FirstName = "Charlie L", LastName = "Ivarock", PhoneNumber = "5555555555" },
                        new { ContactId = 3, Email = "cbesalke@gmail.com", FirstName = "Charlie", LastName = "Besalke", PhoneNumber = "5555555555" }
                    );
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Contribution", b =>
                {
                    b.Property<int>("ContributionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContributerContactId");

                    b.Property<int?>("ContributerContactId1");

                    b.Property<string>("Description");

                    b.Property<int>("EventId");

                    b.HasKey("ContributionId");

                    b.HasIndex("ContributerContactId1");

                    b.HasIndex("EventId");

                    b.ToTable("Contributions");

                    b.HasData(
                        new { ContributionId = 1, ContributerContactId = 1, Description = "10 pounds of ground beef", EventId = 1 }
                    );
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BringAFriend");

                    b.Property<string>("Description");

                    b.Property<string>("DressCode");

                    b.Property<string>("Location");

                    b.Property<int>("OwnerContactId");

                    b.Property<bool>("PublicEvent");

                    b.Property<string>("Title");

                    b.Property<string>("Website");

                    b.HasKey("EventId");

                    b.HasIndex("OwnerContactId");

                    b.ToTable("Events");

                    b.HasData(
                        new { EventId = 2, BringAFriend = false, Description = "I'm lonely and need a party", OwnerContactId = 1, PublicEvent = false, Title = "Teddy's house warming" },
                        new { EventId = 1, BringAFriend = false, Description = "Party!", OwnerContactId = 2, PublicEvent = false, Title = "Charlie Board gaming" },
                        new { EventId = 3, BringAFriend = false, Description = "Charlie will likely win!", OwnerContactId = 3, PublicEvent = false, Title = "Charlie Cube Tournament!" }
                    );
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.EventGuest", b =>
                {
                    b.Property<int>("EventGuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Attending");

                    b.Property<int>("EventId");

                    b.Property<int>("contactGuestId");

                    b.HasKey("EventGuestId");

                    b.HasIndex("EventId");

                    b.HasIndex("contactGuestId");

                    b.ToTable("EventGuests");

                    b.HasData(
                        new { EventGuestId = 1, Attending = false, EventId = 1, contactGuestId = 1 },
                        new { EventGuestId = 2, Attending = false, EventId = 3, contactGuestId = 1 },
                        new { EventGuestId = 3, Attending = false, EventId = 2, contactGuestId = 2 },
                        new { EventGuestId = 4, Attending = false, EventId = 3, contactGuestId = 2 }
                    );
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Chosen");

                    b.Property<DateTime>("EventDate");

                    b.Property<int>("EventId");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EventId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new { ScheduleId = 1, Chosen = false, EventDate = new DateTime(2018, 7, 22, 3, 46, 16, 519, DateTimeKind.Local), EventId = 1 }
                    );
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Contribution", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Contact", "Contributer")
                        .WithMany("Contributions")
                        .HasForeignKey("ContributerContactId1");

                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Event", "Event")
                        .WithMany("Contributions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Event", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Contact", "Owner")
                        .WithMany("OwnedEvents")
                        .HasForeignKey("OwnerContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.EventGuest", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Event", "Event")
                        .WithMany("EventGuests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Contact", "Guest")
                        .WithMany("GuestEvents")
                        .HasForeignKey("contactGuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HackMidwest2018Backend.DatabaseModels.Schedule", b =>
                {
                    b.HasOne("HackMidwest2018Backend.DatabaseModels.Event", "Event")
                        .WithMany("Schedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
